#!/usr/bin/with-contenv bash


if [ "$ENABLE_NGINX" = "TRUE" ] || [ "$ENABLE_NGINX" = "true" ]; then
	### Set Defaults
	LISTEN_PORT=${LISTEN_PORT:-9000}
        
        sed -i -e "s/<LISTEN_PORT>/${LISTEN_PORT}/g" /etc/nginx/conf.d/default.conf
	mkdir -p /var/tmp/nginx
        touch /tmp/state/20-nginx-init
fi

